# Generated by Django 4.1.7 on 2023-03-30 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userForm',
            fields=[
                ('id_user', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='forumPost',
            fields=[
                ('id_post', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='PD')),
                ('postText', models.TextField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.userform')),
            ],
        ),
        migrations.CreateModel(
            name='forumComment',
            fields=[
                ('id_comment', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='CM')),
                ('comment', models.TextField()),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.forumpost')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.userform')),
            ],
        ),
    ]
