# Generated by Django 4.1.7 on 2023-04-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='postTittle',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
