# Generated by Django 4.1.7 on 2023-04-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_forumpost_posttittle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumcomment',
            old_name='id_user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='forumpost',
            old_name='id_user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='id_user',
        ),
        migrations.AlterField(
            model_name='userform',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
